const answerLog = [
  {qNum:1,
  question: 'What was the codename for Windows 95 prior to release?',
  answers: ['Durango','Chicago','Alabaster','Windows 95'],
  correctAnswer: 'Chicago',
  correctIcon: 'https://cdn.drawception.com/images/panels/2012/4-4/pxt3w9PNgz-4.png',
  correctIconAlt: 'terribly drawn 95 logo',
  incorrectIcon: 'https://assets.pcmag.com/media/images/270309-windows-95-98-and-me-blue-screen-of-death.jpg?width=694&height=694&boxFit=y',
  incorrectIconAlt: 'blue screen',
  },
  {qNum:2,
  question: 'Which internet browser launched with Windows 95',
  answers: ['Firefox','Opera','Netscape','Internet Explorer'],
  correctAnswer: 'Internet Explorer',
  correctIcon: 'https://cdn.drawception.com/images/panels/2012/4-4/pxt3w9PNgz-4.png',
  correctIconAlt: 'terribly drawn 95 logo',
  incorrectIcon: 'https://assets.pcmag.com/media/images/270309-windows-95-98-and-me-blue-screen-of-death.jpg?width=694&height=694&boxFit=y',
  incorrectIconAlt: 'blue screen',
  },
  {qNum:3,
  question: 'What band was featured in the promotional release commercial for Windows 95?',
  answers: ['Rolling Stones','The Beatles','Led Zeppelin','Van Halen'],
  correctAnswer: 'Rolling Stones',
  correctIcon: 'https://cdn.drawception.com/images/panels/2012/4-4/pxt3w9PNgz-4.png',
  correctIconAlt: 'terribly drawn 95 logo',
  incorrectIcon: 'https://assets.pcmag.com/media/images/270309-windows-95-98-and-me-blue-screen-of-death.jpg?width=694&height=694&boxFit=y',
  incorrectIconAlt: 'blue screen',
  },
  {qNum:4,
  question: 'Which OS succeeded Windows 95?',
  answers: ['Windows 3.1','Windows 96','Windows 2000','Windows 98'],
  correctAnswer: 'Windows 98',
  correctIcon: 'https://cdn.drawception.com/images/panels/2012/4-4/pxt3w9PNgz-4.png',
  correctIconAlt: 'terribly drawn 95 logo',
  incorrectIcon: 'https://assets.pcmag.com/media/images/270309-windows-95-98-and-me-blue-screen-of-death.jpg?width=694&height=694&boxFit=y',
  incorrectIconAlt: 'blue screen',
  },
  {qNum:5,
  question: 'What popular navigational UI did Microsoft implement with Windows 95?',
  answers: ['Start Menu', 'Icons', 'Folder Search', 'Command-line'],
  correctAnswer: 'Start Menu',
  correctIcon: 'https://cdn.drawception.com/images/panels/2012/4-4/pxt3w9PNgz-4.png',
  correctIconAlt: 'terribly drawn 95 logo',
  incorrectIcon: 'https://assets.pcmag.com/media/images/270309-windows-95-98-and-me-blue-screen-of-death.jpg?width=694&height=694&boxFit=y',
  incorrectIconAlt: 'blue screen',
  },
  {qNum:6,
  question: 'What composer/musician created the startup sound for Windows 95?',
  answers: ['Steve Jobs','Hans Zimmer','John Williams','Brian Eno'],
  correctAnswer: 'Brian Eno',
  correctIcon: 'https://cdn.drawception.com/images/panels/2012/4-4/pxt3w9PNgz-4.png',
  correctIconAlt: 'terribly drawn 95 logo',
  incorrectIcon: 'https://assets.pcmag.com/media/images/270309-windows-95-98-and-me-blue-screen-of-death.jpg?width=694&height=694&boxFit=y',
  incorrectIconAlt: 'blue screen',  
  }
];